FROM p4lang/p4app
LABEL de.hs-fulda.netlab.name="flex/p4-container" \
      de.hs-fulda.netlab.description="P4 and SDN learning environment example VM" \
      de.hs-fulda.netlab.url="https://github.com/prona-p4-learning-platform/p4-container" \
      de.hs-fulda.netlab.vcs-url="https://github.com/prona-p4-learning-platform/p4-container" \
      de.hs-fulda.netlab.docker.cmd="docker run -it --rm -p 3005:3005 -p 3022:22 flex/p4-container"

# lsp lb port
EXPOSE 3005/tcp
# ssh port
EXPOSE 3022/tcp

RUN useradd -m -d /home/p4 -s /bin/bash p4
RUN echo "p4:p4" | chpasswd
RUN echo "p4 ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/99_p4
RUN chmod 440 /etc/sudoers.d/99_p4
WORKDIR /home/p4

RUN apt-get update -y
RUN apt-get install -y curl git openssh-server

RUN curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
RUN sudo apt-get install -y nodejs

RUN git clone https://github.com/jafingerhut/p4-guide
RUN git clone https://github.com/p4lang/tutorials
RUN git clone https://github.com/nsg-ethz/p4-learning
RUN git clone https://github.com/prona-p4-learning-platform/p4-boilerplate

RUN git clone https://github.com/wylieconlon/jsonrpc-ws-proxy
RUN cd jsonrpc-ws-proxy && npm install && npm run prepare

RUN echo 'langservers:\n' \
         '  p4:\n' \
         '    - node\n' \
         '    - /home/p4/p4-vscode-extension/server/build/server.js\n' \
         '    - --stdio\n' >jsonrpc-ws-proxy/servers.yml

RUN git clone https://github.com/prona-p4-learning-platform/p4-vscode-extension.git
RUN cd p4-vscode-extension && npm install && cd server && npm run build && cp -a src/antlr_autogenerated build/

RUN echo '#!/bin/bash\n' \
         'service ssh start\n' \
         'cd /home/p4/jsonrpc-ws-proxy\n' \
         'node dist/server.js --port 3005 --languageServers servers.yml' >start.sh
RUN chmod +x start.sh

ENTRYPOINT ["./start.sh"]
